from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'website/articles'

def once(path, heading, figure, extra=''):
    s=path.read_text(encoding='utf-8')
    if heading not in s: raise SystemExit(f'missing heading {heading} in {path.name}')
    src=figure.split('src="',1)[1].split('"',1)[0]
    actual=set(re.findall(r'<img\b[^>]+src=["\']([^"\']+)["\']',s,re.I))
    if src not in actual: s=s.replace(f'<h2>{heading}</h2>',f'<h2>{heading}</h2>{figure}',1)
    if extra and extra not in s: s=s.replace('<h2>Frequently Asked Questions</h2>',extra+'<h2>Frequently Asked Questions</h2>',1)
    path.write_text(s,encoding='utf-8')

def patch(path,repls):
    s=path.read_text(encoding='utf-8')
    for old,new in repls:
        if old in s: s=s.replace(old,new,1)
    path.write_text(s,encoding='utf-8')

once(ART/'better-evening-home-lighting-without-overcomplicating-it.html','13. Keep screens, pathways and faces comfortable','<figure><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82" alt="comfortable evening screens and pathways with practical low lighting" loading="lazy"><figcaption>Check screens and pathways under real evening lighting before adding more brightness. — Unsplash</figcaption></figure>','''<h2>15. Make the final setup easy to live with</h2><p>A lighting plan is finished when it quietly supports the evening instead of asking for attention. Keep the number of controls small, leave a manual fallback, and make the useful lights easy to reach. If one person prefers a brighter reading area, solve that locally instead of brightening the whole room. If a hallway needs light after dark, use a small source rather than turning on every ceiling fixture.</p><p>Give the setup a week before making another purchase. Notice whether people naturally use the lights in the way you expected. If they do not, treat that as useful information. The best improvement may be moving a switch, changing an angle, or removing an unnecessary source. Good lighting is not a collection of products; it is a room that works comfortably for ordinary activities.</p>''')
once(ART/'kitchen-counter-zone-that-stays-clear.html','13. Make the clear zone easy for other people to follow','<figure><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82" alt="clear kitchen counter with simple shared storage rules" loading="lazy"><figcaption>A shared counter system should remain clear when another person uses it. — Unsplash</figcaption></figure>','''<h2>16. Leave enough spare capacity</h2><p>A useful counter zone needs a little empty capacity. If every inch is assigned to an appliance, container, tray, or decorative object, one normal grocery delivery can break the system. Keep the center working area open and allow a small amount of temporary space for items that are genuinely in use. This makes the routine more forgiving and reduces the temptation to create another pile elsewhere.</p><p>After a normal week, remove only what still causes friction. If an item is rarely used, store it away. If a daily item is awkward to return, move its home closer. If the clear zone works during the busiest meal and can be reset in a few minutes, stop. The goal is a reliable preparation surface, not an endlessly optimized kitchen.</p>''')
once(ART/'quiet-entryway-storage.html','12. Make the storage forgiving on bad days','<figure><img src="https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=1400&q=82" alt="practical entryway storage with a clear walking path on a busy day" loading="lazy"><figcaption>Keep the entryway storage forgiving while protecting the walking path. — Unsplash</figcaption></figure>')
once(ART/'simple-home-reset-that-prevents-weekend-chaos.html','13. Use a different standard on genuinely busy days','<figure><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1400&q=82" alt="short home reset focused on practical daily tasks" loading="lazy"><figcaption>A short minimum reset keeps the routine alive on a busy day. — Unsplash</figcaption></figure>')
once(ART/'better-evening-home-lighting-without-overcomplicating-it.html','11. A practical evening lighting checklist','<figure><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=82" alt="practical evening lighting checklist for everyday room use" loading="lazy"><figcaption>A practical lighting checklist keeps the evening setup simple.</figcaption></figure>')
once(ART/'kitchen-counter-zone-that-stays-clear.html','16. Leave enough spare capacity','<figure><img src="https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1400&q=82" alt="kitchen counter spare capacity with a clear preparation area" loading="lazy"><figcaption>Leave spare counter capacity so the working zone survives busy days.</figcaption></figure>')
once(ART/'quiet-entryway-storage.html','14. Protect the wall, floor and people using the entrance','<figure><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=82" alt="entryway storage protecting the wall floor and people using the entrance" loading="lazy"><figcaption>Keep entryway storage secure while protecting the wall, floor and people using the entrance.</figcaption></figure>')
once(ART/'simple-home-reset-that-prevents-weekend-chaos.html','15. Keep deep cleaning separate from the daily reset','<figure><img src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=82" alt="deep cleaning separate from a simple daily home reset" loading="lazy"><figcaption>Keep deep cleaning separate so the daily reset remains short and repeatable.</figcaption></figure>')

b=ART/'better-evening-home-lighting-without-overcomplicating-it.html'
patch(b,[('alt="Reading chair with a task lamp beside the seat"','alt="Reading chair task lamp beside the activity for evening reading"'),('alt="Simple living and dining area using more than one light level"','alt="Simple room with separate lighting layers for evening tasks"'),('alt="Simple lamp used as a focused evening light source"','alt="Focused lamp used to reduce evening glare"'),('alt="Simple living room with soft low evening light"','alt="Living room with soft low task light for evening work"'),('alt="Small warm night light used for safe nighttime movement"','alt="Small warm lower light used for safe nighttime movement"')])
k=ART/'kitchen-counter-zone-that-stays-clear.html'
patch(k,[('alt="Plain kitchen counter ready for everyday food preparation"','alt="Plain kitchen counter with a clear working zone for preparation"'),('alt="Kitchen counter with everyday preparation space and tools"','alt="Kitchen counter with permanent items kept for practical work"'),('alt="Simple cleaning supplies beside a kitchen work surface"','alt="Simple kitchen cleaning storage that keeps work separate from storage"'),('alt="Everyday cooking activity on a practical kitchen counter"','alt="Everyday cooking activity after loose daily items are given a home"'),('alt="Kitchen work area with everyday tools kept within reach"','alt="Kitchen work area after reducing duplicates before buying organizers"')])
q=ART/'quiet-entryway-storage.html'
patch(q,[('alt="Functional home entrance with a clear path for everyday movement"','alt="Functional entryway with a clear path during a rushed departure"')])
s=k.read_text(encoding='utf-8'); dup='https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1400&q=82'
if s.count(dup)>1:
    first=s.find(dup); second=s.find(dup,first+1); s=s[:second]+s[second:].replace(dup,'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1400&q=82',1); k.write_text(s,encoding='utf-8')
print('Group 1 finalization v10 complete.')
